objects/Delphi_Configuration__c.object
<CustomObject>
    <fields>
        <fullName>Configuration_Type__c</fullName>
        <label>Configuration Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Automatic</fullName>
                </value>
                <value>
                    <fullName>Manual</fullName>
                </value>
                <value>
                    <fullName>None</fullName>
                    <default>true</default>
                    <label>None</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Last_Model_Run__c</fullName>
        <label>Last Model Run</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Last_Prediction_Run__c</fullName>
        <label>Last Prediction Run</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Model_Status__c</fullName>
        <label>Model Status</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Prediction_Status__c</fullName>
        <defaultValue>&quot;Not Started&quot;</defaultValue>
        <label>Prediction Status</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Selected_Field_Account__c</fullName>
        <label>Selected Field Account</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Selected_Field_User__c</fullName>
        <label>Selected Field User</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Selected_Fields__c</fullName>
        <label>Selected Fields</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Time_Prediction_Status__c</fullName>
        <label>Time Prediction Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Delphi Configuration</label>
    <nameField>
        <label>Dephi Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dephi Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Opportunity_Conversion_Probability__c</fullName>
        <label>Opportunity Conversion Probability</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Predicted_Close_Date__c</fullName>
        <description>this field will store the value of time which is calculated based on time prediction code</description>
        <inlineHelpText>this field will store the value of time which is calculated based on time prediction code</inlineHelpText>
        <label>Predicted Close Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Sales_Rep_Recommendation__c</fullName>
        <label>Sales Rep Recommendation</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/DelphiDashboardController.cls
public class DelphiDashboardController{
    public class DataWrapper{
        @AuraEnabled
        public List<Opportunity> oppList;
        @AuraEnabled
        public Map<Id,User> userMap;
        @AuraEnabled
        public Delphi_Configuration__c config;
        public DataWrapper(List<Opportunity> opp,Map<Id,User> uMap,Delphi_Configuration__c del){
            this.oppList=opp;
            this.userMap=uMap;
            this.config=del;
        }
    }
    
    @AuraEnabled
    public static DataWrapper getPredictedOpportunities(){
        Map<Id,User> mapOfUsers=new Map<Id,User>([SELECT Id,Name FROM User]);
        String query='SELECT Id,Name,Opportunity_Conversion_Probability__c,Predicted_Close_Date__c,Sales_Rep_Recommendation__c FROM Opportunity WHERE Opportunity_Conversion_Probability__c!=null AND StageName!=\'Closed Won\' AND StageName!=\'Closed Lost\' ORDER BY Opportunity_Conversion_Probability__c DESC LIMIT 50000 ';
        List<Opportunity> listOfOpps=Database.query(query);
        DataWrapper wrapperToReturn=new DataWrapper(listOfOpps,mapOfUsers,createConfig());
        return wrapperToReturn;
    }
    
    @AuraEnabled
    public static Delphi_Configuration__c createConfig(){
        List<Delphi_Configuration__c> metaType = new List<Delphi_Configuration__c>();
        metaType =[Select id,Configuration_Type__c,Time_Prediction_Status__c,Last_Model_Run__c,Last_Prediction_Run__c,Model_Status__c,Prediction_Status__c,Selected_Fields__c,Selected_Field_Account__c,Selected_Field_User__c from Delphi_Configuration__c];
        if(metaType.size()==0){
            Delphi_Configuration__c   delphi = new Delphi_Configuration__c();
            delphi.Name='Delphi config';
            metaType.add(delphi);
            insert metaType;
        }
        return metaType[0];
    }
}