objects/Delphi_Configuration__c.object
<CustomObject>
    <fields>
        <fullName>Configuration_Type__c</fullName>
        <label>Configuration Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Automatic</fullName>
                </value>
                <value>
                    <fullName>Manual</fullName>
                </value>
                <value>
                    <fullName>None</fullName>
                    <default>true</default>
                    <label>None</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Model_Status__c</fullName>
        <label>Model Status</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Prediction_Status__c</fullName>
        <defaultValue>&quot;Not Started&quot;</defaultValue>
        <label>Prediction Status</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RFE_Fields__c</fullName>
        <label>RFE Fields</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Selected_Field_Account__c</fullName>
        <label>Selected Field Account</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Selected_Field_User__c</fullName>
        <label>Selected Field User</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <label>Delphi Configuration</label>
    <nameField>
        <label>Dephi Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dephi Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/DelphiServicesTest.cls
@isTest
public class DelphiServicesTest{
	@testSetup
    static void setupTestData(){
        Delphi_Configuration__c delphi=new Delphi_Configuration__c(Name='Delphi',Configuration_Type__c='Manual',Prediction_Status__c='Failure',RFE_Fields__c='Name,StageName,AccountId,NextStep,TotalOpportunityQuantity',Selected_Field_Account__c='Name,Industry',Selected_Field_User__c='Name,UserName');
        insert delphi;
    }
    
    @isTest
    static void testCaseOne(){
        ModelService.postValue('Success', 'Name,StageName');
        Delphi_Configuration__c delphi=[SELECT RFE_Fields__c FROM Delphi_Configuration__c LIMIT 1];
    	System.assertEquals('Name,StageName',delphi.RFE_Fields__c);
    }
    
    @isTest
    static void testCaseTwo(){
        ModelServiceSalesRep.postValue('Success');
        Delphi_Configuration__c delphi=[SELECT Model_Status__c FROM Delphi_Configuration__c LIMIT 1];
        System.assertEquals('Success',delphi.Model_Status__c);
    }
    
    @isTest
    static void testCaseThree(){
        PredictionService.postValue('Success');
    	Delphi_Configuration__c delphi=[SELECT Prediction_Status__c FROM Delphi_Configuration__c LIMIT 1];
        System.assertEquals('Failure',delphi.Prediction_Status__c);
    }
    
    @isTest
    static void testCaseFour(){
        PredictionServiceSalesRep.postValue('Success');
        Delphi_Configuration__c delphi=[SELECT Prediction_Status__c FROM Delphi_Configuration__c LIMIT 1];
        System.assertEquals('Success',delphi.Prediction_Status__c);
    }
}