objects/Delphi_Configuration__c.object
<CustomObject>
    <fields>
        <fullName>Configuration_Type__c</fullName>
        <label>Configuration Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Automatic</fullName>
                </value>
                <value>
                    <fullName>Manual</fullName>
                </value>
                <value>
                    <fullName>None</fullName>
                    <default>true</default>
                    <label>None</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>RFE_Fields__c</fullName>
        <label>RFE Fields</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Selected_Field_Account__c</fullName>
        <label>Selected Field Account</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Selected_Field_User__c</fullName>
        <label>Selected Field User</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <label>Delphi Configuration</label>
    <nameField>
        <label>Dephi Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dephi Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/DelphiBatchForPredictionSalesRepTest.cls
@isTest
public class DelphiBatchForPredictionSalesRepTest {
    @TestSetup
    public static void setuptestDataforSalesRepPred(){
        List<Account> accList = new List<Account>();
        accList.add(new Account (Name='Test1'));
        accList.add(new Account(Name='Test2'));
        insert accList;
        List<Opportunity> oppToInsert=new List<Opportunity>();
        for(Integer i=1;i<=10;i++){
            if(Math.mod(i,2)==0)
                oppToInsert.add(new Opportunity(Name='Global Closed Opp',AccountId=accList[0].Id,StageName='Prospecting',CloseDate=System.today()));
            else
                oppToInsert.add(new Opportunity(Name='Local Closed Opp',AccountId=accList[1].Id,StageName='Prospecting',CloseDate=System.today()));
        }
        insert oppToInsert;
        
    }
    @isTest
    public static void TestOne(){
        Delphi_Configuration__c delphi=new Delphi_Configuration__c(Name='Delphi',Configuration_Type__c='Manual',RFE_Fields__c='Name,StageName,AccountId,NextStep,TotalOpportunityQuantity,OwnerId',Selected_Field_Account__c='Name,Industry',Selected_Field_User__c='Name,UserName');
        insert delphi;
        DelphiCalloutBatchForPredictionSalesRep d=new DelphiCalloutBatchForPredictionSalesRep('www.mockcallout.com');
        Database.executeBatch(d,1000);
    }
    
    @isTest
    public static void TestTwo(){
        Delphi_Configuration__c delphi=new Delphi_Configuration__c(Name='Delphi SalesRep',Configuration_Type__c='Automatic',RFE_Fields__c='Name,StageName,AccountId,NextStep,TotalOpportunityQuantity,OwnerId');
        insert delphi;
        DelphiCalloutBatchForPredictionSalesRep d=new DelphiCalloutBatchForPredictionSalesRep('www.mockcallout.com');
        Database.executeBatch(d,1000);
    }
   
    
}