objects/Delphi_Configuration__c.object
<CustomObject>
    <fields>
        <fullName>Last_Model_Run__c</fullName>
        <label>Last Model Run</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Model_Status__c</fullName>
        <label>Model Status</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RFE_Fields__c</fullName>
        <label>RFE Fields</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <label>Delphi Configuration</label>
    <nameField>
        <label>Dephi Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dephi Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ModelService.cls
@RestResource(urlMapping='/modelService/*')
global class ModelService{
    @HttpPost
    global static void postValue(String modelStatus,String oppFieldsAfterRfe){
        System.debug(modelStatus);
        Delphi_Configuration__c configRecord=[SELECT Id,Model_Status__c,RFE_Fields__c,Last_Model_Run__c FROM Delphi_Configuration__c  LIMIT 1];
        configRecord.RFE_Fields__c=oppFieldsAfterRfe;
        update configRecord;
        System.debug(oppFieldsAfterRfe);
        DelphiCalloutBatchForTrainingSalesRep dcObj=new DelphiCalloutBatchForTrainingSalesRep('https://delphi-testing.herokuapp.com/FitModelSalesRep');
        Database.executeBatch(dcObj,1000);
    }
}