objects/Delphi_Configuration__c.object
<CustomObject>
    <fields>
        <fullName>Last_Prediction_Run__c</fullName>
        <label>Last Prediction Run</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Prediction_Status__c</fullName>
        <defaultValue>&quot;Not Started&quot;</defaultValue>
        <label>Prediction Status</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Time_Prediction_Status__c</fullName>
        <label>Time Prediction Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Delphi Configuration</label>
    <nameField>
        <label>Dephi Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dephi Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/PredictionServiceSalesRep.cls
@RestResource(urlMapping='/predictionServiceSalesRep/*')
global class PredictionServiceSalesRep{
    @HttpPost
    global static void postValue(String predStatus){
        System.debug(predStatus);
        Delphi_Configuration__c configRecord=[SELECT Id,Prediction_Status__c,Last_Prediction_Run__c FROM Delphi_Configuration__c  LIMIT 1];
        configRecord.Prediction_Status__c=predStatus.trim();
        configRecord.Last_Prediction_Run__c =System.now();
        configRecord.Time_Prediction_Status__c='Running';
        update configRecord;  
        TimePredictionTrainingBatch t=new TimePredictionTrainingBatch();
        Database.executeBatch(t,1000);
        //DelphiEmailUtility.PostPredictionEmail();
    }
}